services:

  prn232.lms.api:
    build:
      context: .
      dockerfile: PRN232.LMS.API/Dockerfile

    ports:
      - "5001:8080"

    depends_on:
      sqlserver:
        condition: service_healthy

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Server=sqlserver;Database=LMSDB;User Id=sa;Password=YourPassword123!;TrustServerCertificate=True

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"

    ports:
      - "1434:1433"

    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourPassword123!' -Q 'SELECT 1' -No -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s